# Builds assets/trusts.json — alter egos grouped by the role their spell icon
# carries on BG-wiki (Tank / Melee Fighter / Ranged Fighter / Caster / Healer /
# Support / Special). One entry per trust; the app renders it as its own page.
#   job / spells / abilities / ws  -> the stat block at the top of the page
#   acq / feat / syn               -> Acquisition, Special Features, Trust Synergy
# Bullet indentation is carried by leading spaces (2 per level).
# Author: BalladOfWorms
import json

T = []


# Portrait file stem. Derived from the name; only the abbreviated ones need an override.
IMG_OVERRIDE = {
    "Ark Angel EV": "aaev", "Ark Angel HM": "aahm", "Ark Angel TT": "aatt",
    "Ark Angel GK": "aagk", "Ark Angel MR": "aamr", "Domina Shantotto": "d_shantotto",
}


def slug(n):
    s = n.lower().replace(" ", "_").replace("(", "").replace(")", "").replace("'", "")
    while "__" in s:
        s = s.replace("__", "_")
    return s.strip("_")


def t(n, role, job, spells, abilities, ws, acq, feat, syn=None):
    e = {"n": n, "role": role, "job": job, "spells": spells,
         "abilities": abilities, "ws": ws, "acq": acq, "feat": feat}
    if syn:
        e["syn"] = syn
    # img CARRIES ITS FOLDER (same rule as mobs.json) — a bare stem is a silent miss.
    e["img"] = "trustart/%s.jpg" % IMG_OVERRIDE.get(n, slug(n))
    T.append(e)


CIPHER = "Trade the Cipher: {} item to one of the beginning Trust quest NPCs, which may be acquired via:"

t("Amchuchu", "Tank", "Rune Fencer / Warrior",
  ["Flash", "Foil", "Stoneskin", "Refresh", "Phalanx", "Regen I - IV",
   "Protect I - V", "Shell I - V", "Bar-element spells"],
  ["Berserk", "Provoke", "Embolden", "Battuta", "Vallation", "Valiance",
   "Swordplay", "Vivacious Pulse", "Rune Enhancement", "One for All", "Swipe", "Lunge"],
  ["Dimidiation", "Power Slash", "Sickle Moon"],
  [CIPHER.format("Amchuchu"), "  Repeat Login Campaign", "  Mog Pell (Ochre)"],
  ["Possesses Inspiration (50% Fast Cast effect during Vallation, is party-wide during Valiance). Converts 5% of Physical Damage Taken to MP.",
   "Only casts enhancing spells on herself.",
   "Uses Embolden when casting Protect.",
   "She can rapidly generate Volatile Enmity for initial threat or recovery from enmity reset attacks with a cornucopia of abilities and spells like Provoke, Flash, and Foil.",
   "Uses Runes resisting the element of the current day. After taking magic damage, uses the appropriate Bar-spell and changes runes.",
   "Uses One for All in response to enemies casting high-tier damaging spells.",
   "Magic Bursts Level 4 Light or Level 4 Darkness skillchains using Lunge.",
   "Berserk could be a risk when using Amchuchu outside of her role as a magic tank.",
   "Holds up to 3000 TP to close skillchains. Weapon skills are a lower priority."])

t("Ark Angel EV", "Tank", "Paladin / White Mage",
  ["Flash", "Phalanx", "Cure I - IV", "Enlight", "Reprisal"],
  ["Chivalry", "Palisade", "Sentinel", "Divine Emblem", "Rampart", "Shield Strike"],
  ["Chant du Cygne", "Vorpal Blade", "Dominion Slash (AoE)", "Arrogance Incarnate (AoE Spirits Within)"],
  [CIPHER.format("Ark Angel EV"),
   "  Complete Dawn and all its cutscenes.",
   "  Be in possession of the Bundle of scrolls key item.",
   "  Have obtained the additional following Trust spells: Rainemard, & Ark Angel GK.",
   "  Speak with Jamal in Ru'Lude Gardens (H-5).",
   "    After trading Ark Angel GK's cipher, speak to Jamal, zone, and speak to Jamal again to unlock the Objective for Cipher: Ark Angel EV. Be sure before zoning Jamal asks you to \"Please come by again later.\"",
   "  Complete the Records of Eminence Objective: Temper Your Arrogance.",
   "    Warp to Tu'Lia \u2192 Ru'Aun Gardens #4 to battle the Ark Angel with a Phantom gem of arrogance on any difficulty.",
   "Players will be unable to receive the alter ego when trading the Cipher if they have not completed the Rhapsodies of Vana'diel mission \"Exploring the Ruins.\" Completing that cutscene/mission will allow the cipher to be traded."],
  ["Possesses Fast Cast, Cure Potency Bonus +50%, Damage Taken -10%, HP+20%, MP+50%, Converts 5% of Damage Taken to MP.",
   "Lacks Provoke; however, AAEV's additional Fast Cast trait reduces the recast time on Flash and Reprisal for solid enmity control.",
   "  Recast times can be improved further by providing Haste.",
   "AAEV has improved Shield stats compared to other trusts, implied by the Nov 2021 Patch Notes. This would also make her Reprisal better.",
   "Ark Angel Elvaan doesn't use any WHM-only spells, but /WHM has Auto-Regen and Magic Defense Bonus, making her a good physical/magical hybrid tank.",
   "Uses Rampart when her target is under the effects of Chainspell, Manafont, or Astral Flow.",
   "Uses Shield Strike to interrupt enemies casting high tier spells.",
   "Holds up to 2000 TP to try to close skillchains.",
   "With two weapon skills that have no skillchain properties, tends to not interrupt skillchains performed by other party members."],
  ["ArkEV / ArkHM / ArkMR / ArkGK / ArkTT: When all 5 Ark Angels are summoned, they possess a Magic Evasion bonus (see: Resist).",
   "  Estimated 240 Magic Evasion, a 50% increase.",
   "  The bonus is a reference to the Accumulative Magic Resistance that was added to counter the strategy of clearing Divine Might with an alliance of Black Mages."])

t("Ark Angel HM", "Tank", "Ninja / Warrior",
  ["Migawari: Ichi", "Utsusemi: Ichi/Ni", "Hojo: Ichi/Ni", "Kurayami: Ichi/Ni"],
  ["Innin", "Yonin", "Provoke", "Berserk", "Warcry"],
  ["Chant du Cygne", "Swift Blade", "Cross Reaver (Unique Conal Stun)"],
  [CIPHER.format("Ark Angel HM"),
   "  Complete Dawn and all its cutscenes.",
   "  Be in possession of the Bundle of scrolls key item.",
   "  Have obtained the additional following Trust spells: Rainemard, Ark Angel GK, Ark Angel EV, Ark Angel MR, & Ark Angel TT.",
   "  Speak with Jamal in Ru'Lude Gardens (H-5).",
   "    After trading Ark Angel TT's cipher, you must speak to Jamal, zone, and speak to Jamal again to unlock the Objective for Cipher: Ark Angel HM. Be sure before zoning Jamal asks you to \"Please come by again later.\"",
   "    You may need to zone in again if you haven't talked to him since trading Ark Angel TT's cipher in order for him to unlock the Objective.",
   "  Complete the Records of Eminence Objective: Eliminate Your Apathy.",
   "    Warp to Tu'Lia \u2192 Ru'Aun Gardens #1 to battle the Ark Angel with a Phantom gem of apathy on any difficulty.",
   "Players will be unable to receive the alter ego when trading the Cipher if they have not completed the Rhapsodies of Vana'diel mission \"Exploring the Ruins.\" Completing that cutscene/mission will allow the cipher to be traded."],
  ["Possesses HP+20%.",
   "Possesses an Utsusemi +1 trait which grants AA HM an extra shadow.",
   "If there is a NIN, PLD, or RUN in the party, behaves as a damage dealer: Uses Innin, Berserk.",
   "If there are no other tanks in the party, behaves as a tank: Uses Yonin, Warcry.",
   "Uses Provoke in both situations in order to sub tank.",
   "Casts debuffs when does not have hate.",
   "Starts fights with Migawari if available.",
   "Uses weapon skills at 1000 TP and does not try to skillchain."],
  ["ArkEV / ArkHM / ArkMR / ArkGK / ArkTT: When all 5 Ark Angels are summoned, they possess a Magic Evasion bonus (see: Resist).",
   "  Estimated 240 Magic Evasion, a 50% increase.",
   "  The bonus is a reference to the Accumulative Magic Resistance that was added to counter the strategy of clearing Divine Might with an alliance of Black Mages."])

t("August", "Tank", "Paladin / Warrior",
  ["Cure I - IV", "Flash", "Holy II", "Reprisal"],
  ["Sentinel", "Provoke", "Divine Emblem", "Palisade", "Daybreak (Wings)"],
  ["Neutral: Alabaster Burst, Null Field, Tartaric Sigil",
   "Daybreak: Fulminous Fury, Noble Frenzy, No Quarter"],
  [CIPHER.format("August"), "  Sinister Reign", "  Mog Pell (Ochre)",
   "  Records of Eminence Quest Way Over Capacity"],
  ["Possesses HP+10%.",
   "Uses Divine Emblem to enhance Holy II.",
   "August's attacks are not affected by Sambas.",
   "August automatically applies all Killer Effects and high resistance to Terror.",
   "August wears the Founder's Gear and has significantly less damage.",
   "He can switch weapons at will while auto attacking and performing weapon skills; it is unknown if this changes his damage type or is merely cosmetic.",
   "He has been observed wielding H2H, Dagger and Axe, Bow (Auto Attacks), Great Axe and Scythe (Alabaster Burst), Great Sword (Tartaric Sigil), Dual Katanas and Great Katana (Noble Frenzy), Club and Staff (Fulminous Fury), and Flute (Daybreak) in addition to his default Sword and Shield.",
   "August is considered to be wielding a Great Sword for the purposes of Damage Limit+ and Inundation.",
   "Uses weapon skills at 1000 TP and does not try to skillchain.",
   "Daybreak (~3 min cooldown, ~1 min 30 sec duration):",
   "  When August's HP drops below a certain threshold (~66%), he uses Daybreak if it's available which partially restores some HP and MP, resets his TP, and activates an aura with wings of light.",
   "  Daybreak is a -50% PDT effect, full Erase, Stats boost, Regen, and Store TP.",
   "  During Daybreak, August's next weapon skill will be Fulminous Fury or Noble Frenzy, followed by No Quarter.",
   "  Daybreak is removed after the use of No Quarter.",
   "  Daybreak's cooldown may start when No Quarter is used (meaning it's about a 1.5 min cooldown)."])

t("Curilla", "Tank", "Paladin / Paladin",
  ["Cure I - IV", "Flash"],
  ["Sentinel"],
  ["(5) Red Lotus Blade", "(25) Seraph Blade", "(50) Swift Blade", "(60) Vorpal Blade"],
  ["Complete the initiation quest in San d'Oria.",
   "Must be Rank 3 or higher in any nation.",
   "  Speak with Curilla in Chateau d'Oraguille at (I-9)."],
  ["Possesses MP+30%, Guardian (Sentinel enmity loss -95%), Sentinel Recast merited (-50 sec), Cure Potency Bonus +25%, and Cure Casting Time Down.",
   "Does not use Provoke, but will use Flash. This leads to poor hate control.",
   "Uses TP randomly and does not try to skillchain.",
   "Cures players and trusts in yellow (<75%) HP."],
  ["Curilla: Rainemard casts Phalanx II (unlocked at level 75) only on Curilla and himself. His Phalanx, like his Enspells, also appears to benefit from his extremely high enhancing magic skill; his Phalanx II is -35 damage."])

t("Gessho", "Tank", "Ninja / Warrior",
  ["Utsusemi: Ichi/Ni", "Hojo: Ichi/Ni", "Kurayami: Ichi/Ni"],
  ["Provoke", "Yonin", "Shiko no Mitate (Yagudo Parry)", "Rinpyotosha (Yagudo Howl: Attack Boost)"],
  ["Happobarai (Yagudo Sweep)", "Hane Fubuki (Feather Storm)", "Shibaraku (AoE)"],
  ["Complete Passing Glory.", "  Examine the cushion in Aht Urhgan Whitegate (J-12)."],
  ["Will only use the highest tier debuff available, but will use both Utsusemi spells.",
   "Will maintain Yonin full time.",
   "Greatly benefits from capping magical haste as it will allow for better maintenance of Utsusemi shadows.",
   "Holds TP until 1500 to try to close skillchains.",
   "Gessho is a good tank choice for players trying to avoid Light-based damage since his weapon skills won't accidentally open Light skillchains.",
   "Special abilities:",
   "  Shiko no Mitate: Defense Boost + Stoneskin + Issekigan",
   "  Rinpyotosha: Party members gain a 3 minute Attack Boost (+25% Attack) effect. 5 minute cooldown."])

t("Mnejing", "Tank", "Paladin / Paladin \"Valoredge\"",
  [],
  ["Strobe I - II (Provoke)", "Shield Bash (Stun)", "Disruptor (Dispel)", "Flashbulb (Flash)"],
  ["Chimera Ripper", "String Clipper", "Shield Subverter (Conal AoE, Silence)"],
  [CIPHER.format("Mnejing"), "  Repeat Login Campaign", "  Mog Pell (Ochre)"],
  ["Passive -37.5% Damage Taken Reduction.",
   "Possesses lower HP than most tanks, but takes significantly less damage.",
   "Possesses a moderate amount of MP, despite the fact he cannot use magic.",
   "Possesses Barrier Module (Increased Block Chance, Shield Mastery).",
   "Mnejing will hold up to 1500 TP to close skillchains; however, he will not always choose to close with a weapon skill which will create the highest tier skillchain possible.",
   "  (i.e. he will sometimes use Chimera Ripper to skillchain with Savage Blade to create a tier 1 skillchain instead of Savage Blade to create a tier 3 skillchain)",
   "Mnejing tries to interrupt TP abilities with Shield Bash.",
   "Mnejing will Flash its target using the Flashbulb (Mnejing's Flash generates considerable enmity).",
   "Mnejing can use the effects of his attachments (Strobe, Barrier Module, Flashbulb, and Disruptor) despite not having any maneuvers effects.",
   "Mnejing's Disruptor Dispel is highly accurate and he will use it against enemies others will not attempt to dispel due to M.ACC."],
  ["Nashmeira: Mnejing receives increased defense (+10%) and increased enmity (+10%) (not compatible with Nashmeira II)."])

t("Rahal", "Tank", "Paladin / Warrior",
  ["Cure I - IV", "Flash", "Phalanx", "Enlight"],
  ["Sentinel", "Berserk", "Provoke", "Shield Bash"],
  ["Fast Blade", "Seraph Blade", "Swift Blade", "Savage Blade"],
  [CIPHER.format("Rahal"), "  Repeat Login Campaign", "  Mog Pell (Ochre)"],
  ["Possesses Dragon Killer.",
   "Rahal is an aggressive tank who uses Berserk.",
   "Prioritizes Flash over Provoke.",
   "Will only cast Cure when a party member is below 33% health and will use the highest tier available.",
   "Will only use Sentinel when he is below 33% health.",
   "He tries to interrupt TP abilities and high-tier spells with Shield Bash.",
   "Holds up to 2500 TP to close skillchains."])

t("Rughadjeen", "Tank", "Paladin / Paladin",
  ["Holy", "Flash", "Cure I - IV", "Raise"],
  ["Sentinel", "Divine Emblem", "Holy Circle", "Chivalry"],
  ["Power Slash", "Sickle Moon", "Ground Strike", "Victory Beacon (Conal AoE)"],
  [CIPHER.format("Rughadjeen"), "  Repeat Login Campaign", "  Mog Pell (Red)", "  Mog Pell (Ochre)"],
  ["Possesses Fast Cast, Cure Potency Received +30%, Damage Taken -5%, HP+20%, MP+20%.",
   "He wields the Algol and so has an enfire effect and a 3% triple attack rate.",
   "Uses Holy Circle if the enemy is Undead.",
   "Will only cast Cure I - IV when a party member is below 75% (yellow) HP or asleep.",
   "Tries to use weapon skills at 1000 TP, but it is lower priority.",
   "Uses Chivalry at 50% MP if it's available.",
   "Will cast Raise on KO'd party members in casting range."],
  ["Mihli Aliapoh / Gadalar / Zazarg / Najelith: Rughadjeen empowers the other serpent generals.",
   "  Mihli Aliapoh gains +25% Cure Potency increase.",
   "  Gadalar gains +25 Magic Attack Bonus. For a total +90 MAB at level 99 (+40 BLM job traits, +25 Gadalar trait, +25 Synergy).",
   "  Najelith gains +40 ranged accuracy and enhanced Barrage accuracy.",
   "  Zazarg gains ~5-15% damage.",
   "When any other serpent generals are in the party, Rughadjeen has Damage Taken -29% while in combat with a foe."])

t("Trion", "Tank", "Paladin / Warrior",
  ["Cure I - IV", "Flash"],
  ["Provoke", "Sentinel"],
  ["Red Lotus Blade", "Savage Blade", "Royal Bash (Shield Bash)", "Royal Savior (Palisade, Sentinel, Stoneskin)"],
  ["Complete the initiation quest in San d'Oria.",
   "Must be Rank 6 or higher in any nation.",
   "  Examine the \"Door: Prince Royal's Room\" in Chateau d'Oraguille at (H-7)."],
  ["Royal Bash is stronger than a normal Shield Bash. Royal Saviour is a secondary, stronger version of Sentinel. Trion alternates between this and the normal version of Sentinel.",
   "Trion tries to interrupt TP abilities with Royal Bash.",
   "Uses TP randomly and does not try to skillchain.",
   "With his two defensive TP moves, he's not likely to interrupt skillchains much."],
  ["Pieuje (UC) only uses Regen when healing his brother Trion."])

t("Valaineral", "Tank", "Paladin / Warrior",
  ["Cure I - IV", "Flash", "Protect IV - V", "Reprisal", "Enlight", "Phalanx"],
  ["Provoke", "Sentinel", "Majesty", "Defender", "Fealty", "Divine Emblem", "Chivalry", "Palisade", "Rampart"],
  ["Circle Blade", "Sanguine Blade", "Savage Blade", "Uriel Blade (AoE)"],
  [CIPHER.format("Valaineral"),
   "  Records of Eminence: Basic Tutorial Objective Reward",
   "  Repeat Login Campaign", "  Mog Pell (Ochre)"],
  ["Possesses Enmity+, Cure Potency Bonus+50%, Spell interruption rate decrease, Refresh+ (+3mp/tick Auto Refresh, stacks with PLD trait), and Damage Taken -8%, HP+10%, MP+20%.",
   "Uriel Blade can be used under 1000 TP based on certain conditions, making him excellent at engaging multiple targets. He can even use it when engaging a single target and any time the player draws enmity. This makes him a good SC opener for Ark Angel GK, who can use that to close Light SCs right after engaging an enemy with no TP requirement for either of them.",
   "Very powerful at low levels due to his special ability letting him use Uriel Blade before he has access to it as a normal weapon skill (lv.50).",
   "Casts Protect spells on himself under the effect of Majesty with the added defense of Shield Barrier (defense varies by iM, up to 350), but does not attempt to overwrite other Protect effects even if he would gain more defense from doing so.",
   "Uses Divine Emblem before casting Flash if it is available.",
   "Rampart will be used when his target is under the effects of Chainspell, Manafont, or Astral Flow.",
   "  Against SMNs, Rampart trigger seems to be based on whether there's an avatar summoned. Certain Tonberry NMs have a Light Spirit or their avatar appears after Astral Flow, which could explain why Rampart didn't trigger.",
   "Fealty can be used under certain conditions including anticipating Mijin Gakure and negating its damage.",
   "Uses weapon skills randomly around 2000 TP and does not try to skillchains."])


# ---------------------------------------------------------------- RANGED FIGHTER

t("Elivira", "Ranged Fighter", "Ranger / Warrior",
  [],
  ["Berserk", "Barrage", "Decoy Shot", "Double Shot"],
  ["Coronach", "Slug Shot", "Heavy Shot", "Split Shot"],
  [CIPHER.format("Elivira"), "  Repeat Login Campaign", "  Mog Pell (Ochre)"],
  ["Possesses Store TP-30, Melee Attacks and Ranged Attacks: TP+100%.",
   "When using Coronach, Elivira benefits from the relic aftermath (enmity -10).",
   "Elivira will melee the enemy if in range and perform ranged attacks regardless of position.",
   "Elivira will hold her position when engaging an enemy, she will neither move in or out.",
   "Summoning Elivira early in the trust order helps to ensure she is in melee range and increase her TP gain.",
   "Elivira tends to use TP immediately upon reaching 1000%; however, she will close a skillchain if possible.",
   "Gains 127 TP with Sword hits, 178 TP with Marksmanship."])

t("Makki-Chebukki", "Ranged Fighter", "Ranger / Black Mage",
  [],
  ["Flashy Shot", "Sharpshot", "Barrage"],
  ["Sidewinder", "Empyreal Arrow", "Dulling Arrow", "Flaming Arrow"],
  [CIPHER.format("Makki"), "  Repeat Login Campaign", "  Mog Pell (Ochre)"],
  ["Possesses MP+100%, Store TP-40, Ranged Attacks: TP+100%.",
   "Will try to stay out of melee range.",
   "Uses weapon skills at 2000 TP and does not try to skillchain.",
   "During Lightsday, Makki-Chebukki will move out of range but take no other actions. As soon as the day changes he will resume fighting normally (resummoning is not necessary).",
   "Gains 168 TP per attack."])

t("Margret", "Ranged Fighter", "Ranger / Thief",
  [],
  ["Decoy Shot", "Double Shot", "Barrage", "Sharpshot", "Stealth Shot"],
  ["Sidewinder", "Arching Arrow", "Refulgent Arrow", "Piercing Arrow"],
  [CIPHER.format("Margret"), "  Repeat Login Campaign", "  Mog Pell (Ochre)"],
  ["Possesses Treasure Hunter, Store TP+40, Ranged Attacks: TP+100%.",
   "Will try to stay out of melee range.",
   "Margret tends to support her TP abilities with as many job abilities as possible.",
   "Uses weapon skills at 2000 TP and does not try to skillchain.",
   "If the enemy has less than a certain threshold of HP (10-15%), Margret will hold off using weapon skills or abilities and only auto-attack.",
   "Margret is fairly poor at opening or closing high tier skillchains due to only having a single weaponskill with dual element properties (Arching Arrow).",
   "Gains 252 TP per attack."])

t("Najelith", "Ranged Fighter", "Ranger / Ranger",
  [],
  ["Barrage", "Double Shot"],
  ["Cyclone", "Sidewinder", "Empyreal Arrow", "Typhonic Arrow (Conal AoE)"],
  [CIPHER.format("Najelith"), "  Repeat Login Campaign", "  Mog Pell (Red)", "  Mog Pell (Ochre)"],
  ["Possesses enhanced Critical Hit Rate, Melee Attacks and Ranged Attacks: TP+100%.",
   "Holds position while engaged and performs ranged attacks.",
   "Melee attacks and performs ranged attacks if in melee range.",
   "Holds TP till about 1500% in an attempt to close a skillchain.",
   "Tends to use Cyclone if allowed to weapon skill outside of a skillchain."],
  ["Rughadjeen empowers the other serpent generals.",
   "  Najelith gains +40 ranged accuracy and enhanced Barrage accuracy.",
   "  Rughadjeen has Damage Taken -29% while in combat with a foe."])

t("Semih Lafihna", "Ranged Fighter", "Ranger / Warrior",
  [],
  ["Sharpshot", "Barrage", "Stealth Shot", "Double Shot"],
  ["Sidewinder", "Arching Arrow", "Stellar Arrow (AoE)", "Lux Arrow"],
  [CIPHER.format("Semih"),
   "  Speak to Kupipi in Heavens Tower during Mission 2-3 for any nation (Journey Abroad / The Emissary / The Three Kingdoms).",
   "  Alternatively speak to Kupipi in Heavens Tower once the Rhapsodies of Vana'diel Mission 1-7 (The Path Untraveled) is complete."],
  ["Possesses Store TP+40, Ranged Attacks: TP+100%.",
   "Will try to stay out of melee range.",
   "Semih Lafihna will hold up to 2000 TP to try to close skillchains.",
   "Lux Arrow and Stellar Arrow are both able to close Tier 3 skillchains and can close double tier 3 skillchains as well.",
   "Exercise caution when using Semih around multiple foes as Stellar Arrow is an AoE attack centered around its target.",
   "She is an extremely strong trust to use while leveling up due to her access to Sidewinder and Arching Arrow at low levels.",
   "Sidewinder is her best WS for damage, use Lux Arrow for Defense Down, Stellar Arrow for Evasion Down.",
   "Gains 252 TP per hit."])

t("Tenzen II", "Ranged Fighter", "Samurai / Ranger",
  [], [],
  ["Oisoya"],
  [CIPHER.format("Tenzen II"), "  Complete Crashing Waves."],
  ["Possesses Store TP+10, Ranged Attacks: TP+100%.",
   "Will try to stay out of melee range.",
   "Oisoya is a variant of Namas Arrow with identical enmity properties.",
   "Gains 252 TP per hit maximum when over level 90, based on Samurai Store TP traits.",
   "Only uses his weaponskill to open skillchains when another party member has 1000 TP. Will wait at 3000 TP indefinitely if no other party members gain TP."])

# ----------------------------------------------------------------------- CASTER

t("Adelheid", "Caster", "Scholar / Black Mage",
  ["Cure I - IV", "Helices", "Single-target elemental nukes I - V", "Storms", "Stun"],
  ["Dark Arts", "Addendum: Black"],
  ["Binding Microtube", "Paralyzing Microtube", "Silencing Microtube", "Twirling Dervish (AoE)"],
  [CIPHER.format("Adelheid"), "  Records of Eminence: Basic Tutorial Objective Reward",
   "  Repeat Login Campaign", "  Mog Pell (Ochre)"],
  ["Adelheid casts a Storm on herself corresponding to the enemy's weakness if possible, otherwise matches the current day, followed by a -helix and nukes of her storm's element unless magic bursting a skillchain.",
   "  Will change storms under certain conditions such as BLMs casting Freeze (which modifies enemy resistances).",
   "  For Light/Dark storms, she only casts helix since there are no matching elemental nukes.",
   "During a skillchain, magic bursts a helix matching the skillchain's element without preparing a -storm first.",
   "Casts Stun to interrupt enemy TP moves.",
   "Casts Cure spells on party members under 33% (red) hp, with a higher threshold and priority for the tank.",
   "Despite using Dark Arts, her healing potency/cost/cast times do not appear to suffer any detrimental effects.",
   "Gains 100 TP per hit with her melee attacks. Tries to use TP as soon as she gets it, but may have other priorities.",
   "Adelheid's weapon skills all do magic damage and the Microtubes additionally apply status effects.",
   "Her weapon skills seem to have a longer delay before you can skillchain with them: try timing follow-up weapon skills starting from when the vial explodes, not from when the ability is used.",
   "Twirling Dervish requires level 50."])

t("Ajido-Marujido", "Caster", "Black Mage / Red Mage",
  ["Cure I - IV", "Dispel", "Single-target elemental nukes I - V", "Slow", "Paralyze"],
  [], [],
  ["Complete the initiation quest in Windurst.",
   "Must be Rank 6 or higher in any nation.",
   "  Speak to Apururu in Windurst Woods at (H-9).",
   "  May not be obtained if the player is currently between Windurst Missions 6-1 to 9-2. Even if you changed Nations \u2014 you must change back to Windurst and complete Missions."],
  ["Possesses Cure Potency Bonus+25%, Fast Cast Bonus, Magic Burst Bonus, A+ skill in Elemental, Enfeebling, and Healing magic skill.",
   "Does not melee, but instead uses short-ranged palm blasts.",
   "Possesses neither TP moves nor abilities that utilize TP.",
   "Ajido-Marujido prioritizes Dispel over elemental spells.",
   "Ajido-Marujido will not attempt to cast elemental/enfeebling magic on an enemy that is sure to resist it.",
   "When he draws hate, he will stop casting spells and start to use his weak attacks until the enemy attacks someone else.",
   "Ajido-Marujido has higher ratings in his magic skills than normal black mages."],
  ["Apururu: Apururu will prioritize supporting her brother, Ajido-Marujido.",
   "  Status Removal and Haste priority changes to Ajido-Marujido > Player > Herself > Others.",
   "  If multiple party members meet the conditions for Devotion, will use it on Ajido-Marujido preferentially.",
   "  Apururu gains +25% Cure Potency Bonus."])

t("Ark Angel TT", "Caster", "Black Mage / Dark Knight",
  ["Single-target elemental nukes I - V", "Sleepga/II", "Bio/II", "Poison/II", "Aspir", "Stun"],
  ["Elemental Seal", "Last Resort", "Souleater"],
  ["Guillotine", "Amon Drive (AoE Paralyze+Petrify)"],
  [CIPHER.format("Ark TT"),
   "  Complete Dawn and all its cutscenes.",
   "  Be in possession of the Bundle of scrolls key item.",
   "  Have obtained the additional following Trust spells: Rainemard, Ark Angel GK, Ark Angel EV, & Ark Angel MR.",
   "  Speak with Jamal in Ru'Lude Gardens (H-5).",
   "    After trading Ark Angel MR's cipher, you must speak to Jamal, zone, and speak to Jamal again to unlock the Objective for Cipher: Ark TT. Be sure before zoning Jamal asks you to \"Please come by again later.\"",
   "  Complete the Records of Eminence Objective: Overcome your Cowardice.",
   "    Warp to Tu'Lia \u2192 Ru'Aun Gardens #2 to battle the Ark Angel with a Phantom gem of cowardice on any difficulty.",
   "Players will be unable to receive the alter ego when trading the Cipher if they have not completed the Rhapsodies of Vana'diel mission \"Exploring the Ruins.\" Completing that cutscene/mission will allow the cipher to be traded."],
  ["Possesses HP+20%, MP+50%.",
   "Ark Angel Tarutaru uses Last Resort and Souleater whenever the recast is ready and tries to keep up Poison and Bio fulltime on the enemy.",
   "At the start of the fight and each time after using Amon Drive, he casts Sleepga, augmented by Elemental Seal if the recast is ready.",
   "He only casts elemental spells to magic burst skillchains, often trying to burst two spells on the same skillchain (the second burst failing most of the time due to high casting times).",
   "Aspir is used to burst Compression-skillchains and also casted freely when his MP is below 50%, but are only used against enemies which have MP.",
   "Will also Sleep/Sleep II single target enemies.",
   "Casts Stun based on enemy TP moves.",
   "Uses weapon skills at 2000 TP and does not try to skillchain.",
   "Avoids casting spells that would be resisted.",
   "  Elemental Seal prioritized Sleep spells, but can be used for Poison II on Sleep-immune enemies.",
   "Does not magic burst targets where he doesn't have enough magic accuracy."],
  ["ArkEV / ArkHM / ArkMR / ArkGK / ArkTT: When all 5 Ark Angels are summoned, they possess a Magic Evasion bonus (see: Resist).",
   "  Estimated 240 Magic Evasion, a 50% increase.",
   "  The bonus is a reference to the Accumulative Magic Resistance that was added to counter the strategy of clearing Divine Might with an alliance of Black Mages."])

t("Domina Shantotto", "Caster", "Black Mage / Dark Knight",
  ["Single-target elemental nukes I - V"],
  [],
  ["Guillotine", "Cross Reaper", "Shadow of Death", "Salvation Scythe"],
  [CIPHER.format("Domina"), "  Repeat Login Campaign", "  Mog Pell (Red)", "  Mog Pell (Ochre)"],
  ["Starts battles with Tier V nukes before meleeing.",
   "Occasionally nukes as long as she isn't in the top enmity slot, does not try to magic burst.",
   "  Spells are used more often against enemies resistant to slashing damage, such as elementals.",
   "Only uses darkness-aligned elemental spells, ignoring enemy weakness.",
   "Salvation Scythe inflicts Poison, Bio, Paralyze and Slow.",
   "Uses weapon skills at 1000 TP."])

t("Gadalar", "Caster", "Black Mage / Black Mage",
  ["Firaga I - III", "Blaze Spikes"],
  [],
  ["Spinning Scythe", "Spiral Hell", "Salamander Flame (AoE Fire)", "Vorpal Scythe"],
  ["Complete Embers of His Past.",
   "  Speak to Fari-Wari in Aht Urhgan Whitegate (K-12).",
   "Players will be unable to receive the alter ego if he is being held prisoner by beastmen forces in Besieged."],
  ["Possesses MP+25%, Magic Attack Bonus+25.",
   "Favors Firaga III regardless of surrounding enemies.",
   "  Avoids casting spells that would have a low Magic Hit Rate, also uses lower tier spells depending on magic accuracy and level.",
   "Gadalar recovers MP when he is hit with physical attacks.",
   "Uses TP as soon as he gets it.",
   "Favors Salamander Flame, a unique AoE weapon skill that also applies Dia III for 30 seconds."],
  ["Rughadjeen empowers the other serpent generals.",
   "  Gadalar gains +25 Magic Attack Bonus. For a total +90 MAB at level 99 (+40 BLM job traits, +25 Gadalar trait, +25 Synergy).",
   "  Rughadjeen has Damage Taken -29% while in combat with a foe."])

t("Ingrid", "Caster", "White Mage / White Mage",
  ["Haste", "Banish I - III", "Cursna"],
  [],
  ["Seraph Strike", "Judgment", "Hexa Strike"],
  ["Complete The Merciless One.",
   "  Speak with Rigobertine in Eastern Adoulin (J-7).",
   "Players will be unable to receive the alter ego between the time the mission Beauty and the Beast is undertaken and the mission Glimmer of Portent is completed."],
  ["Possesses Undead Killer, Banish effectiveness vs Undead +10 (28/256).",
   "Engages and closes in to melee her target. (Ingrid gains 100 TP/hit)",
   "Holds up to 1500 TP in order to close skillchains.",
   "Cycles through Banish spells (highest tier to lowest), making her useful for Undead targets.",
   "Places extreme priority on using Cursna should any party members be Doomed/Cursed.",
   "Casts Haste on the player regardless of job and on other party members with melee jobs."])

t("Kayeel-Payeel", "Caster", "Black Mage / Summoner",
  ["Single-target elemental nukes I - V", "Multi-target elemental nukes I - III", "-aja", "Ancient Magic/II"],
  [],
  ["Gate of Tartarus", "Tartarus Torpor (AoE Sleep, M.Def/M.Eva down)", "Sunburst"],
  [CIPHER.format("Kayeel"), "  Repeat Login Campaign", "  Mog Pell (Ochre)"],
  ["Kayeel-Payeel has a very high amount of Fast Cast and tries to magic burst spells.",
   "He can only cast spells of the Ice and Lightning elements, ignores enemy weaknesses.",
   "Quickly burns through his MP with spells like Burst II/Freeze II and -aja III spells.",
   "He benefits from the relic aftermath of Gate of Tartarus (refresh 8 mp/tick) and will use it when he runs out of MP.",
   "Does not engage, but will attack with his staff if the enemy is nearby.",
   "Uses weapon skills at 1500 TP but does not try to skillchain."],
  ["Robel-Akbel: Robel-Akbel and Kayeel-Payeel will cast spells much more frequently: improved Fast Cast effect."])

t("Kukki-Chebukki", "Caster", "Black Mage / Black Mage",
  ["Single-target elemental nukes I - V", "Multi-target elemental nukes I - III", "-aja",
   "Elemental Debuff spells", "Sleepga I - II"],
  [], [],
  [CIPHER.format("Kukki"), "  Repeat Login Campaign", "  Mog Pell (Ochre)"],
  ["Tries to stay a distance (~15) away from the monster when he doesn't have hate.",
   "Kukki-Chebukki just uses spells matching the element the current day.",
   "  On Darksday, he only casts Sleepga II and Sleepga (doesn't have Bio, Drain, or Aspir).",
   "  On Lightsday, does nothing along with Makki-Chebukki since he has no Light-based spells.",
   "Casts lower-tier spells against enemies with low HP to conserve MP.",
   "Gains TP from Occult Acumen trait but can't use it."],
  ["When all three are present, Makki-Chebukki can cause Kukki-Chebukki to cast Meteor by shouting \"MEEE\". Kukki-Chebukki and Cherukiki may join with \"TEEE\" and \"ORRR!\" which increases the damage of the spell. A player-BLM CAN join this Meteor-casting.",
   "They gain a small amount of mp when they do their emotes.",
   "  They take turns emoting, so it's like the 3 of them have 1 Refresh (+3mp/tick) effect that they have to share."])

t("Leonoyne", "Caster", "Black Mage / Paladin",
  ["Ice Spikes", "Blizzaga I - III"],
  [],
  ["Freezebite", "Herculean Slash", "Shockwave", "Spine Chiller (Terror)"],
  [CIPHER.format("Leonoyne"), "  Repeat Login Campaign", "  Mog Pell (Ochre)"],
  ["Possesses MP+25%.",
   "Spine Chiller causes a short duration Terror effect (extremely low proc rate).",
   "Casts Ice Spikes if it's not active.",
   "Weapon skills at 1000% regardless of skillchain condition.",
   "Favors Blizzaga III regardless of surrounding enemies.",
   "  Avoids casting spells that would have a low Magic Hit Rate, also uses lower tier spells depending on magic accuracy and level.",
   "Has permanent Enblizzard effect (30+ damage even at low levels).",
   "Leonoyne recovers MP when he is hit with physical attacks."])

t("Mumor II", "Caster", "Black Mage / Dancer",
  ["Single-target elemental nukes I - V", "Stun", "-ja Spells (Magic Burst + Aura only)"],
  ["Firesday Night Fever (boost to all status, grants visible aura)"],
  ["Lovely Miracle Waltz", "Shining Summer Samba", "Neo Crystal Jig", "Super Crusher Jig",
   "Eternal Vana Illusion", "Final Eternal Heart (AoE)"],
  [CIPHER.format("Mumor II"), "  Sunbreeze Festivals",
   "    You have to get a \"perfect score\" (8 dancing syncs) twice. (First to get the costume outfit, and then a second time in said outfit to get the Trust Cipher.)",
   "  Mog Pell (Ochre)"],
  ["Possesses HP+15%.",
   "Uses highest-tier elemental magic spell available, avoids casting spells that the enemy is resistant to but doesn't accurately target enemy weaknesses.",
   "  Tends to run out of MP very quickly. Firesday Night Fever will fully recover MP, but she only uses it at low HP.",
   "Stays in melee range and attacks with her wands, does not appear to be affected by Haste.",
   "Casts Stun to interrupt enemy TP moves.",
   "Firesday Night Fever (5 min cooldown, ~4 min duration):",
   "  When her HP drops below 50%, uses Firesday Night Fever if it's available which fully recovers her HP and MP.",
   "  Has a pink sparkling aura.",
   "  No longer freely casts single target nukes. Only casts during magic burst using -ja spells or to cast Stun.",
   "  Will use her weapon skills in this order: Neo Crystal Jig \u2192 Super Crusher Jig \u2192 Eternal Vana Illusion \u2192 Final Eternal Heart (AoE).",
   "  Firesday Night Fever ends when she uses Final Eternal Heart.",
   "  Firesday Night Fever lasts about 4 minutes, based on her low attack rate and TP gain.",
   "    Glitch: if Mumor lands the finishing blow on an enemy with Final Eternal Heart the aura does not stop, she no longer uses weapon skills, and cannot re-activate Firesday Night Fever to heal herself."])

t("Ovjang", "Caster", "Red Mage / Black Mage \"Stormwaker\"",
  ["Slow", "Silence", "Paralyze", "Dispel", "Single-target elemental nukes I - IV"],
  [],
  ["Sixth Element", "Knockout", "Slapstick"],
  [CIPHER.format("Ovjang"), "  Repeat Login Campaign", "  Mog Pell (Ochre)"],
  ["Possesses MP+20%.",
   "Holds TP until 1500 to try to close skillchains.",
   "Gains TP slowly: she occasionally attacks between casts.",
   "Prioritizes Dispel.",
   "Prefers Sixth Element."],
  ["Nashmeira: Ovjang receives reduced enmity (-10%) and increased magic damage (+10%)."])

t("Robel-Akbel", "Caster", "Black Mage / Summoner",
  ["Single-target elemental nukes I - V", "-aja", "Stun"],
  [],
  ["Spirit Taker", "Null Blast (restores MP equal to damage dealt)", "Quietus Sphere (AoE Dark)"],
  [CIPHER.format("Robel-Akbel"), "  Repeat Login Campaign", "  Mog Pell (Ochre)"],
  ["Robel-Akbel avoids casting elemental magic that his target would resist. Does not accurately target weaknesses.",
   "Attempts to magic burst off skillchains using -aja tier spells.",
   "  Robel will often try to double burst a skillchain but rarely succeeds without some kind of external fast cast bonus.",
   "Robel-Akbel will use elemental magic of a tier that is sufficient to KO his current target (assuming the attack is not resisted), thus conserving his MP for future battles.",
   "Unlike most magic wielding trusts, Robel-Akbel can sustain his magic attacks for long periods of time due to Occult Acumen and Null Blast (which he prioritizes when low on MP).",
   "Casts Stun in response to enemy TP moves.",
   "Will stand in place after engaging, only attacking enemies with his staff if they are within melee range.",
   "Gains TP from casting spells and can use certain weapon skills at range.",
   "Uses weapon skills at 2000 TP. Does not try to skillchain.",
   "  Null Blast \u2014 converts damage dealt to MP. Additional effect: Magic Evasion Down."],
  ["Kayeel-Payeel: Robel-Akbel and Kayeel-Payeel will cast spells much more frequently: improved Fast Cast effect.",
   "Karaha-Baruha: Robel-Akbel opens skillchains when Karaha-Baruha is at 1000 TP."])

t("Rosulatia", "Caster", "Black Mage / Dark Knight",
  ["Stone I - V"],
  [],
  ["Baneful Blades", "Depraved Dandia", "Dryad Kiss (Haste+Regen)", "Matriarchal Fiat (AoE)",
   "Wildwood Indignation"],
  [CIPHER.format("Rosulatia"), "  Sinister Reign", "  Mog Pell (Ochre)",
   "  Records of Eminence Quest Over Capacity"],
  ["Possesses HP+30%, MP+100%.",
   "Casts only earth elemental magic spells.",
   "Like other non-humanoids, has a large amount of max HP and MP.",
   "Stops casting spells when in the top enmity slot.",
   "Melee attacks are special moves; she does not benefit from Sambas or Haste, but likewise is not affected by Slow or Spikes.",
   "  Tree Spike; Vines (+Bind); Twister (+Silence).",
   "Uses Dryad Kiss at yellow HP (<75%) to gain a strong Regen (amount depends on iM).",
   "Uses TP randomly.",
   "Does not try to magic burst.",
   "Rosulatia is a plantoid, so she can intimidate beasts and is intimidated by vermin."])

t("Shantotto", "Caster", "Black Mage / Black Mage",
  ["Single-target elemental nukes I - V"],
  [], [],
  ["Complete the initiation quest in San d'Oria, Bastok, and Windurst.",
   "Have obtained the following Trust spells: Kupipi, Nanaa Mihgo, Ajido-Marujido, Excenmille, Curilla, Trion, Ayame, Naji, & Volker.",
   "  Complete Curses, Foiled A-Golem!?.",
   "  Speak to Shantotto in Windurst Walls at (K-7)."],
  ["When Shantotto draws hate, she will stop casting until the enemy attacks someone else.",
   "Shantotto will use the highest tier of elemental magic she can access by default.",
   "If fighting a weaker enemy or an enemy at low HP, Shantotto will use lower tier spells in order to conserve her MP."],
  ["King of Hearts uses the full range of his enhancing spells on Shantotto in the same way as on himself and his player and even prioritizes her over the player and himself. (Does not apply to Shantotto II or Domina Shantotto)"])

t("Shantotto II", "Caster", "Black Mage / White Mage",
  ["Single-target elemental nukes I"],
  [],
  ["(5) Lesson in Pain", "(25) Empirical Research", "(50) Final Exam", "(50) Doctor's Orders"],
  [CIPHER.format("Shantotto II"), "  Repeat Login Campaign", "  Mog Pell (Ochre)"],
  ["Possesses HP-10%, BLM/WHM traits with additional Magic Burst Bonus+30, Elemental Magic Damage+ based on iM.",
   "Auto-attacks are magic damage of all elements, damage type is the element with the lowest resistance.",
   "Shantotto only uses tier 1 spells; however, she possesses extremely high Elemental Magic Damage+.",
   "  This Elemental Magic Damage+ only affects spells, unlike the Magic Damage (Statistic) which would affect Weapon Skill and Skillchain Damage.",
   "  Elemental Magic Damage+ varies by level: +784 at iM 120 (+979 with the standard Magic Damage+195 that caster trusts receive at iM).",
   "  Magic Attack Bonus is the standard amount: BLM Trait value, with an additional +25 at iM which may require Rhapsody in Fuchsia for total of +65.",
   "Shantotto's tier 1 magic spells are comparable in power to spells appropriate to her actual level.",
   "As a result of only using tier 1 magic she will almost never run out of MP regardless of the duration of a battle.",
   "Shantotto will magic burst any skillchains, and she often double bursts for massive damage in a very short period of time.",
   "Due to all of these factors Shantotto is widely regarded as the absolute best trust available for magic damage and magic bursting.",
   "However, she has relatively low HP and defenses making her very fragile and susceptible to dying from enemy AoE attacks.",
   "When aiming for magic burst and casting normally, avoids casting spells based on enemy resistances but doesn't accurately target weaknesses if multiple elements meet a certain magic accuracy threshold.",
   "Shantotto will hold up to 2500 TP to close skillchains.",
   "Lesson in Pain \u2014 damage and Magic Evasion Down.",
   "Empirical Research \u2014 damage and 25 Magic Defense Down.",
   "Final Exam \u2014 damage.",
   "Doctor's Orders \u2014 damage."])

t("Ullegore", "Caster", "Black Mage / Dark Knight",
  ["Single-target elemental nukes I - V", "Comet", "Stun"],
  [],
  ["Bored to Tears (Slow)", "Envoutement", "Memento Mori (M.Atk. Boost)", "Silence Seal (AoE Silence)"],
  [CIPHER.format("Ullegore"), "  Repeat Login Campaign", "  Mog Pell (Ochre)"],
  ["Possesses a massive MP pool (approx 5000 at i119), HP+30%, MP+300%.",
   "Will use Memento Mori before casting Comet.",
   "Casts Stun to interrupt enemy TP moves.",
   "Ullegore is thematically a Corse: he uses Corse abilities as weaponskills, and can intimidate Arcana.",
   "But since he is a man in a costume, does not exhibit Undead traits: Ullegore can be cured, he is not intimidated by Arcana, and HP/MP can be drained from him with Drain/Aspir.",
   "Likewise, he does not exhibit Demon traits, even if he is called a Demon King on his Trust cipher.",
   "Ullegore's Envoutement skill does not apply Curse like a normal Corse.",
   "Uses a unique attack Bored to Tears, which is accompanied by a message stating that \"The <target> has become noticeably bored.\" This applies a Slow less potent than Slow II."])

# ----------------------------------------------------------------------- HEALER

t("Apururu (UC)", "Healer", "White Mage / Red Mage",
  ["Cure I - VI", "Curaga I - V", "Protect/ra I - V", "Shell/ra I - V", "-na Spells", "Erase",
   "Stoneskin", "Haste"],
  ["Martyr", "Devotion", "Convert"],
  ["(50) Nott"],
  ["Be a member of the Apururu Unity Concord.",
   "  Obtain 5000 Unity Accolades through Records of Eminence objectives for a Partial Personal Evaluation of 5pt (this is also how you re-obtain it in the event you've lost it)."],
  ["Possesses Regain (75 TP/tick).",
   "Does not melee or cast spells on enemies, relying on Regain for TP.",
   "Uses TP to recover MP. It is a low priority, and at 3000 TP she may continue casting Cure until she is out of MP.",
   "  The really high Regain compared to other trusts is balanced by the high MP cost of Curaga.",
   "Will use Curaga spells when 3 or more party members are in yellow HP (<75%) or asleep.",
   "Casts Haste on the player, herself, and melee damage dealers in the party (with the exception of NIN).",
   "Uses Convert and Martyr only at very low MP (<10%).",
   "Casts Stoneskin on herself and tries to keep it applied.",
   "Uses Devotion on party members that have <20% MP.",
   "Tries to stay a distance (~15) away from the monster when she doesn't have hate.",
   "Devotion and Martyr have a shorter range (10.6'), so pay attention to her movements if you need those effects."],
  ["Apururu will prioritize supporting her brother Ajido-Marujido.",
   "  Status Removal and Haste priority changes to Ajido-Marujido > Player > Herself > Others.",
   "  If multiple party members meet the conditions for Devotion, will use it on Ajido-Marujido preferentially.",
   "  Apururu gains +25% Cure Potency Bonus."])

t("Cherukiki", "Healer", "White Mage / Black Mage",
  ["Cure I - VI", "Protect/ra I - V", "Shell/ra I - V", "Regen I - IV", "Haste", "Slow",
   "Paralyze", "Silence"],
  [], [],
  ["Complete One to be Feared.",
   "  Speak with Taillegeas in Ru'Lude Gardens (I-7).",
   "Players will be unable to receive the alter ego between the time the mission The Warrior's Path is offered and the boss of the mission Dawn is defeated."],
  ["Possesses Regen Effect merits, Enhanced Regen potency.",
   "Does not engage.",
   "Favors Regen spells over Cure spells.",
   "Tries to stay a distance (~15) away from the monster when she doesn't have hate.",
   "Native Regen effect of 5hp/tick.",
   "Casts Haste on the player, herself, and melee damage dealers in the party (with the exception of NIN)."],
  ["Kukki-Chebukki & Makki-Chebukki: Will assist casting Meteor on enemy.",
   "  They gain a short Refresh effect when they do their emotes.",
   "  They take turns emoting, so it's like the 3 of them have 1 Refresh (+3mp/tick) effect that they have to share."])

t("Ferreous Coffin", "Healer", "White Mage / Warrior",
  ["Cure I - VI", "Raise I - III", "-na Spells", "Haste"],
  [],
  ["Randgrith"],
  [CIPHER.format("F. Coffin"), "  Repeat Login Campaign", "  Mog Pell (Ochre)"],
  ["Auto Refresh II, HP-10%, MP+35%.",
   "Will only cast Raise III on KO'd party members in casting range.",
   "Will only cast status ailment removal spells on the player with the highest enmity.",
   "Has a high Cursna success rate (only casts on the highest threat player).",
   "Ferreous Coffin only uses Randgrith and benefits from relic aftermath (acc. +20).",
   "Will use TP as soon as he gets it, so he is good at maintaining enemy Evasion Down and initiating Light skillchains.",
   "Casts Haste on party members regardless of job."])

t("Karaha-Baruha", "Healer", "White Mage / Summoner",
  ["Cure I - VI", "Protect/ra I - V", "Shell/ra I - V", "-na Spells", "Haste", "Barelementra"],
  [],
  ["Spirit Taker", "Sunburst", "Starburst", "Howling Moon (AoE)", "Lunar Bay"],
  [CIPHER.format("Karaha"), "  Repeat Login Campaign", "  Mog Pell (Red)", "  Mog Pell (Ochre)"],
  ["HP-10%, MP+20%.",
   "Possesses very high max MP and low HP on par with Summoner main-job. Has the lowest HP among the healers.",
   "Will attempt to close a Skillchain so long as he has 1000 or more TP.",
   "Will save his TP until 3000 to use Spirit Taker if unable to close a skillchain and he has less than full MP.",
   "Will cast Barelementra after taking damage from a skill or spell with elemental properties."],
  ["Star Sibyl: Karaha-Baruha gains an additional 2 MP/tick auto-refresh (3 MP/tick total) while engaged with a foe.",
   "  Karaha-Baruha uses Dark weapon skills which deal more damage with Star Sibyl's Indi-Acumen effect.",
   "Robel-Akbel: Robel will prioritize opening skillchains for Karaha to close."])

t("Kupipi", "Healer", "White Mage / White Mage",
  ["Cure I - VI", "Protect/ra I - V", "Shell/ra I - V", "-na Spells", "Slow", "Paralyze", "Erase"],
  [],
  ["Starlight", "Moonlight"],
  ["Complete the initiation quest in Windurst."],
  ["Prioritizes immediate removal of status ailments.",
   "Will stay in place after engaging up to 20 yalms, allowing the player to pull the monster away. If pulled beyond that, she will move to be within 15 yalms.",
   "Uses Cure spells on party members in orange HP (<50%) or asleep, with higher priority for the tank or current target of the foe (<75%).",
   "Will cast single target Protect and Shell on players that get dispelled or otherwise lack the buff.",
   "  Prioritizes -na and then healing spells over buffing and finally enfeebling.",
   "    Enfeebling is the lowest priority. Casts Slow first followed by Paralyze, and casts no other enfeebles.",
   "  Overwrites a lower tier Protect or Shell with a higher tier single target if applicable."])

t("Mihli Aliapoh", "Healer", "White Mage / White Mage",
  ["Cure I - VI", "Protect/ra I - V", "Shell/ra I - V", "-na Spells", "Slow", "Paralyze"],
  ["Afflatus Solace"],
  ["True Strike", "Brainshaker", "Hexa Strike", "Scouring Bubbles (AoE)"],
  [CIPHER.format("Mihli"), "  Records of Eminence: Basic Tutorial Objective Reward",
   "  Repeat Login Campaign", "  Mog Pell (Ochre)"],
  ["Possesses Cure Potency Bonus+5%.",
   "Possesses Healing Magic Skill+; estimated to be 500.",
   "  Compared to other trusts, this translates to about another 5% increase to the base Cure and +2% Cursna success rate.",
   "Prioritizes herself first with status removal.",
   "Uses Cure spells on party members in orange HP (<50%) or asleep, with higher priority for the tank (<75%).",
   "Uses TP randomly and does not try to skillchain.",
   "  Prefers using Scouring Bubbles WS."],
  ["Rughadjeen empowers the other serpent generals.",
   "  Mihli Aliapoh gains +25% Cure Potency increase. (Cure VI: 1033 hp \u2192 1279 hp)",
   "  Rughadjeen has Damage Taken -29% while in combat with a foe."])

t("Monberaux", "Healer", "Paladin / Rune Fencer \"Chemist\"",
  [],
  ["Cover", "Mix (see Special Features)"],
  [],
  ["Acquired from A.M.A.N. Validator after reaching a total of 480 Deeds. (They are not spent.)"],
  ["Possesses MP-90%.",
   "  His iM stat gains are the same as a tank's. Fashioned after the Final Fantasy V job, Chemists have high stamina and a magic penalty.",
   "  Has typical PLD job traits such as Resist Sleep and Tenacity.",
   "  Internal PLD job impacts behavior of trust supports like Koru-Moru or off-tanks like Ark HM and behavior of certain enemies like Bozetto Necronura.",
   "If you drew enmity and are being targeted, Monberaux will use Cover if you stand behind him.",
   "Does not engage.",
   "Functionally immune to Paralyze.",
   "  Can be affected by the Paralysis status, but it cannot proc in any meaningful way as all weaponskills (which Monberaux's item uses count as) cannot be paralyzed.",
   "Muddle, the status preventing usage of items, will prevent him from using Chemist abilities.",
   "  Chemist abilities can still be used while under the effect of Amnesia.",
   "Status removal abilities become AoE after donating Gil to Monberaux. Donation amount is 10% of the Gil you currently have on hand, with a 10,000g lower limit and 100,000g upper limit. Donating more does not change the effect. Upgrade lasts until the next Conquest Tally.",
   "  This can be manipulated to always get the lower price \u2014 temporarily move Gil into your Mog Garden Gil repository chest, or an alt character, and keep just 100,000 Gil (or less) on you. You can move your Gil back after the trade.",
   "Uses one ability every 3-4 seconds as needed.",
   "Uses the following abilities:",
   "  Potion: restores 50 HP.",
   "  X-Potion: restores 150 HP.",
   "  Hyper Potion: restores 250 HP.",
   "  Max. Potion: restores 500 HP.",
   "  Mix: Max. Potion: restores 700 HP.",
   "  Mix: Final Elixir: restores HP/MP fully in an area up to two times. Requires Elixir and Hi-Elixir donation to Monberaux in Upper Jeuno. Used when a party member is asleep.",
   "  Mix: Panacea-1: removes erasable ailments.",
   "  Mix: Gold Needle: removes Petrification.",
   "  Mix: Vaccine: removes Plague.",
   "  Mix: Para-b-gone: removes Paralyze.",
   "  Mix: Antidote: removes Poison.",
   "  Mix: Eye Drops: removes Blind.",
   "  Vaccine: removes Plague.",
   "  Echo Drops: removes Silence.",
   "  Holy Water: removes Curse, Zombie, and Doom.",
   "  Mix: Guard Drink: grants Protect (220 defense, 5 minutes, AoE) and Shell (-29% MDT, 5 minutes, AoE). Sheltered Ring and Brachyura Earring do not apply.",
   "  Mix: Insomniant: grants Monberaux Negate Sleep.",
   "Mix II \u2014 these potions share a 60 second cooldown. Used with high priority.",
   "  Mix: Life Water: grants Regen (20/tick, 1 minute, AoE).",
   "  Mix: Elemental Power: grants Magic Attack Boost (+20, 1 minute, AoE).",
   "  Mix: Dragon Shield: grants Magic Defense Boost (+10, 1 minute, AoE).",
   "  Mix: Samson's Strength: grants STR/DEX/VIT/AGI/INT/MND/CHR Boost (+10, 1 minute, AoE).",
   "  Mix: Dark Potion: deals magical damage (666 fixed damage, ignores resistance and magic defense).",
   "Mix III \u2014 potions with a separate 90 second cooldown.",
   "  Mix: Dry Ether Concoction: restores 160 MP."])

t("Nashmeira II", "Healer", "White Mage / Puppetmaster",
  ["Cure I - VI", "Curaga I - V", "-na spells", "Erase"],
  [],
  ["Imperial Authority (Stun)"],
  [CIPHER.format("Nashmeira II"), "  Complete Aphmau's Light."],
  ["Possesses HP-10%, MP+15%.",
   "Uses Curaga spells when 3 or more party members are below 75% hp or affected by sleep.",
   "Uses Imperial Authority at 1000 TP."])

t("Pieuje (UC)", "Healer", "White Mage / Paladin",
  ["Cure I - VI", "-na Spells", "Erase", "Esuna", "Protect/ra I - V", "Shell/ra I - V", "Auspice", "Haste"],
  ["Afflatus Misery", "Sacrosanctity"],
  ["(5) Starlight", "(25) Moonlight", "(50) Nott"],
  ["Be a member of the Pieuje Unity Concord.",
   "  Obtain 5000 Unity Accolades through Records of Eminence objectives for a Partial Personal Evaluation of 5pt."],
  ["Possesses Regain (34 TP/tick), WHM/PLD traits including Auto Refresh and Resist Sleep.",
   "Stays in place after engaging, but will attack with a club if the enemy is nearby.",
   "  When positioned in attack range, he will be able to use MP recovery moves more often, making up for his lower max MP compared to Tarutaru trusts.",
   "Afflatus Misery and Auspice together give him an Enlight effect, increasing his accuracy.",
   "Will use Esuna in Misery stance, removing 2 debuffs from himself and any other party members in range with the same debuff.",
   "Casts Haste on players regardless of job.",
   "Sacrosanctity defends your party from enemy SP abilities like Manafont, Chainspell, and Astral Flow.",
   "Uses TP for MP recovery. Prefers Nott."],
  ["Trion: Pieuje only uses Regen on Trion. Pieuje prioritizes Trion > Player > Others when casting Haste and -na Spells."])

t("Yoran-Oran (UC)", "Healer", "White Mage / Black Mage",
  ["Protectra I - V", "Shellra I - V", "-na spells", "Cure I - VI", "Erase", "Stoneskin"],
  ["Afflatus Solace"],
  ["(50) Nott"],
  ["Be a member of the Yoran-Oran Unity Concord.",
   "  Obtain 5000 Unity Accolades through Records of Eminence objectives for a Partial Personal Evaluation of 5pt."],
  ["Possesses Cure Potency Bonus+50%, Fast Cast, Regain (50/tick).",
   "Depending on Unity rank: MP+15%~+25%.",
   "Does not melee or cast spells on enemies, relying on Regain for TP.",
   "Uses TP to recover MP. It is a low priority, and at 3000 TP he may continue casting Cure until he is out of MP.",
   "Very high magic evasion for a trust. Will occasionally sleep but avoids silence and other enfeebles with a very high success rate.",
   "Is very mana efficient thanks to Afflatus Solace, Conserve MP, and capped Cure Potency.",
   "Tries to keep himself buffed with Stoneskin.",
   "Stays at a distance from enemies while healing."])

t("Ygnas", "Healer", "White Mage / Paladin",
  ["Cure I - VI", "Protect/ra I - V", "Shell/ra I - V", "-na Spells", "Erase", "Haste"],
  [],
  ["Deific Gambol (AoE)", "Phototropic Blessing", "Phototropic Wrath", "Sacred Caper"],
  ["Complete The Ygnas Directive and then The Arciela Directive Records of Eminence Objectives.",
   "  Examine the Sandy Overlook in Ceizak Battlegrounds (J-10) after fulfilling the other prerequisites."],
  ["Possesses HP+10%, MP+10%, Cure Potency +50%, Fast Cast +50%, Converts 5% of \"Cure\" amount to MP, Regain (30 TP/tick).",
   "  MP cost reduction can be over 50% for Cure III and over 30% for Cure VI before Day/Weather/Cure Potency Received+ bonuses.",
   "Ygnas prefers to heal with his most mp efficient healing spell, which is Cure III at level 99.",
   "  Uses Cure III on the tank at yellow HP (<75%) or other party members at orange HP (<60%).",
   "  Uses Cure VI on party members at low HP (<45%).",
   "Can be intimidated when curing party members who have Plantoid Killer.",
   "Will not engage, and stands out of range.",
   "Will not use a weaponskill until reaching 3,000 TP unless party members have taken damage, much like Selh'teus.",
   "  Deific Gambol causes AoE damage.",
   "  Phototropic Blessing is an AoE Heal, 30/tick Regen, +25% Defense, and MDB+ for 60 seconds.",
   "  Phototropic Wrath is an AoE Haste II, attack +25%, MAB+, and 23 damage Enlight (decays by 1 each hit) for 60 seconds.",
   "  Sacred Caper inflicts damage and Rasp."],
  ["Arciela or Arciela II: Ygnas will gain a 2/tick Indi-Refresh."])

ROLES = ["Tank", "Melee Fighter", "Ranged Fighter", "Caster", "Healer", "Support", "Special"]
out = {"roles": ROLES, "trusts": sorted(T, key=lambda x: x["n"])}
path = "/home/claude/android/app/src/main/assets/trusts.json"
with open(path, "w", encoding="utf-8") as f:
    json.dump(out, f, ensure_ascii=False, separators=(", ", ": "))

import collections, os
print("trusts:", len(T), collections.Counter(x["role"] for x in T))
bad = [x["n"] for x in T if x["role"] not in ROLES]
print("bad roles:", bad)
missing = [x["n"] for x in T
           if not os.path.exists("/home/claude/android/app/src/main/assets/" + x["img"])]
print("missing portraits:", missing)
assert not missing
